"""initial migration

Revision ID: 451642c8fcb5
Revises: 
Create Date: 2021-01-17 03:08:27.394145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '451642c8fcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('opened', sa.DateTime(), nullable=False),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('author_association', sa.Enum('MEMBER', 'OWNER', 'MANNEQUIN', 'COLLABORATOR', 'CONTRIBUTOR', 'FIRST_TIME_CONTRIBUTOR', 'FIRST_TIMER', 'NONE', name='authorassociation'), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('pull_request',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('opened', sa.DateTime(), nullable=False),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('author_association', sa.Enum('MEMBER', 'OWNER', 'MANNEQUIN', 'COLLABORATOR', 'CONTRIBUTOR', 'FIRST_TIME_CONTRIBUTOR', 'FIRST_TIMER', 'NONE', name='authorassociation'), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'ERROR', 'FAILURE', 'PENDING', 'SUCCESS', name='statuscheckstatus'), nullable=True),
    sa.Column('merged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request')
    op.drop_table('issue')
    op.drop_table('user')
    op.drop_table('repository')
    # ### end Alembic commands ###
